### ISSUE TITLE
 kbd build race 

### ISSUE THREAD

**Issue by maxinbjohn** [legionus/kbd#1]
Reporting a strange build race in kbd (version 2.0.3):

| make[3]: Entering directory `/data/poky-master/tmp/work/ppc7400-poky-linux/kbd/2.0.2-r0/build/data'
| cp -r /data/poky-master/tmp/work/ppc7400-poky-linux/kbd/2.0.2-r0/kbd-2.0.2/data/keymaps keymaps_Z
| cp -r /data/poky-master/tmp/work/ppc7400-poky-linux/kbd/2.0.2-r0/kbd-2.0.2/data/consolefonts consolefonts_Z
| cp -r /data/poky-master/tmp/work/ppc7400-poky-linux/kbd/2.0.2-r0/kbd-2.0.2/data/partialfonts partialfonts_Z
| chmod -R u+w keymaps_Z
| chmod -R u+w consolefonts_Z partialfonts_Z
| cd keymaps_Z && gzip -f -n -9 */*.map */*/*.map
| chmod: cannot read directory`consolefonts_Z/README.Cyrillic': Not a directory
| make[3]: **\* [consolefonts_Z] Error 1
| make[3]: **\* Waiting for unfinished jobs....
| make[3]: Leaving directory `/data/poky-master/tmp/work/ppc7400-poky-linux/kbd/2.0.2-r0/build/data'

More info: 
https://bugzilla.yoctoproject.org/show_bug.cgi?id=7436

**Comment by legionus** [comment]
@maxinbjohn I can't reproduce it. Please give more information.

**Comment by maxinbjohn** [comment]
This build error was reported in parallel build environment (with "make -j install")

Yes, It is hard to reproduce and failure occurs randomly. Tried a number of times today, It didn't occur this time.

**Comment by legionus** [comment]
No movement.
