### ISSUE TITLE
Why `conspath`?

### ISSUE THREAD

**Issue by nnym** [legionus/kbd#106]
https://github.com/legionus/kbd/blob/d27e4a38e7cb0a0ff0665e8017425911a7cc04f0/src/libcommon/getfd.c#L13-L21

I first came across it in [vtcol](https://gitlab.com/phgsng/vtcol/-/blob/730010a9474143ac4481d53e47dbb1aa582afe34/src/lib.rs?page=2#L1221-1228) and assumed that it was excessive because one of [`ttyname`](https://pubs.opengroup.org/onlinepubs/9699919799/functions/ttyname.html) and `/dev/tty` would suffice; but then I found [linux-vt-setcolors](https://github.com/evanpurkhiser/linux-vt-setcolors/blob/1dccf7c77f43331b671b6a401c06cf5d919812df/setcolors.c#L25-L33) and then this—the original—and now I'm intrigued: what is the reason for this? I was unable to find any explanation in the commit log.

**Comment by legionus** [comment]
@nnym This code was written in the days before git. When git came out I imported tarballs.

This code was written in the days when /dev was manually filled with device files. Some of them might be missing. 

The `getfd()` job is to find a suitable terminal device and open the descriptor. The calling program may not have the terminal descriptor as stdin/stdout/stderr. This descriptor is needed to call ioctls.

The `ttyname` takes file descriptor and return its name. That is, the descriptor should already be opened on the terminal. Here are some examples of implementing this function:

https://github.com/bminor/musl/blob/master/src/unistd/ttyname_r.c
https://github.com/bminor/glibc/blob/master/sysdeps/posix/ttyname_r.c

So I don't understand how `ttyname` can help me in `getfd`.

**Comment by nnym** [comment]
I see. That explains it; thanks. You're right about `ttyname`; I missed that it takes a file descriptor. I assumed that it would do the right thing since it's what coreutils' `tty` uses and I hadn't seen it fail until I ran `tty` with input redirection just a while ago.
