### ISSUE TITLE
Feature request / proposal: setfont -big

### ISSUE THREAD

**Issue by mhoye** [legionus/kbd#107]
Given the large variety of screen sizes and resolutions out there now, occasionally I'm looking at a screen where default-sized text is so small as to be unreadable and it would be nice to reliably have something simple I could type blind that would give me a usable console. "setfont -d" doesn't work reliably, for me at least.

Would this project accept a patch such that "setfont -big"  (or -B or whatever) would set the console font to some large, predefined font, something in the Terminus32 group?

**Comment by legionus** [comment]
The `setfont` has `-d` option (Double size of font horizontally and vertically). Doesn't this work for you?

Also after kbd v2.6-rc1 the new maximum font size is increased to 64x128, but I don’t have such fonts as part of the package.

**Comment by mhoye** [comment]
Ah, I see my misunderstanding. I'm using a custom console font that is already larger than 16x16 so setfont on this machine is changing my console font to the double-size of a standard font. So, I see the font change but stay the same size.

I'm glad to hear about the larger 64x128 fonts on the way.

**Comment by legionus** [comment]
> I'm glad to hear about the larger 64x128 fonts on the way.

A new ioctl was added to the 6.2 kernel which adds support for tall fonts. You can create a psf2 font taller than 32 pixels. The new maximum font size has been raised to 64x128. The `setfont` can load such font into the kernel.

**Comment by legionus** [comment]
> > I'm looking at a screen where default-sized text is so small as to be unreadable
> 
> 100 % agree. Happens to me all the time in many different Linux systems. Never quite understood why this obssession with tiny unreadable fonts by default. Maybe some (decades old) legacy reason ?

Kernel has a default font and keymap. This default font is suitable for all types of terminals. Modern distributions can and should change them depending on the type and parameters of the current terminal. This can be done in the initramfs or in the booted system.

> I'm just a user. I've been searching for psf2 fonts bigger than 32 for a long time. Cant find anything on the internet. It is really hard to find even 32 pixel size modern good looking fonts for the Linux console. The only one I am aware and using for a lot of years are the "Terminus" family. Package is called "terminus-font" on Archlinux.
> 
> All the other fonts shipped with the "kbd" package are very lotz for very ancient and tiny stuff which I, personally, dont see the need for.

Well, I don't make fonts. I distribute fonts that authors give me and if the licenses for these fonts allow it. For example Red Hat supports eurlatgr and sends me updates.

> Do you happen to know any other modern, good looking bigger than 32 font ? Is there even a "market" for this ? Are there actually developers interested and working on this ?

I don't know anything about this.

> And if those fonts do exists, would the "kbd" package be including them in the future ?

If anyone creates such a font under a free license, I will include it in the package.

**Comment by mhoye** [comment]
Can you try some of these fonts, and see if they work?

https://github.com/mhoye/128x64

**Comment by legionus** [comment]
Currently there are no console types in the kernel that support fonts larger than 32x32 (See [link](https://github.com/legionus/kbd/issues/109#issuecomment-1936223538) for explanation). The kbd has support for loading tall fonts. When the kernel itself learns to work with them (paradox), then such fonts can be loaded into the kernel using current kbd.
