### ISSUE TITLE
LOADKEYS(1) | non-existing path for `defkeymap.map`

### ISSUE THREAD

**Issue by Ricky-Tigg** [legionus/kbd#113]
_kbd package installed from Fedora repository_

Hello.

reference in `LOADKEYS(1)`:

`If the -d (or --default ) option is given, loadkeys loads a default keymap, probably the file defkeymap.map either in /usr/lib/kbd/keymaps or in /usr/src/linux/drivers/char.`

- Path `/usr/lib/kbd/keymaps` exists.
- Path` /usr/src/linux/drivers/char` doesn't exist.
```
$ ls /usr/src/
debug  kernels
$ locate defkeymap.map
/usr/lib/kbd/keymaps/legacy/i386/qwerty/defkeymap.map.gz
```

**Comment by legionus** [comment]
There is indeed a mistake. The path where defkeymap.map is alternatively searched is slightly different. The second path is `/usr/src/linux/drivers/tty/vt` . This is an optional path to the linux kernel source code.

**Comment by legionus** [comment]
@Ricky-Tigg The loadkeys utility uses multiple directories to search for keymaps. At the beginning defkeymap is searched among other keymaps. If defkeymap is not found, loadkeys will try searching the kernel source tree if the directory exists.

https://github.com/legionus/kbd/blob/master/data/keymaps/i386/qwerty/defkeymap.map

**Comment by legionus** [comment]
I think so.

**Comment by legionus** [comment]
> There is indeed a mistake. The path where defkeymap.map is alternatively searched is slightly different. The second path is `/usr/src/linux/drivers/tty/vt` . This is an optional path to the linux kernel source code.

Fixed in master.
