### ISSUE TITLE
`loadkeys`| No change of VC Keymap in the current session

### ISSUE THREAD

**Issue by Ricky-Tigg** [legionus/kbd#114]
v. 2.6.4 | Package kbd from Fedora Linux repository

Hello.
```
$ loadkeys us
Couldn't get a file descriptor referring to the console.
$ sudo loadkeys us
$ localectl
System Locale: LANG=fi_FI.UTF-8
    VC Keymap: fi
   X11 Layout: fi
    X11 Model: pc105
```

In the current session no change into `us` happened in respect to _VC Keymap_.

**Comment by legionus** [comment]
@Ricky-Tigg Are you running the utility in a terminal emulator?
