### ISSUE TITLE
`kbd_mode` |keyboard declared as being in an unknown mode

### ISSUE THREAD

**Issue by Ricky-Tigg** [legionus/kbd#115]
v. 2.6.4 | Package kbd from Fedora Linux repository

Hello.

```
$ kbd_mode
Couldn't get a file descriptor referring to the console.
$ sudo kbd_mode
The keyboard is in some unknown mode
```
Is it not so however that the mode cannot be other than one of these: RAW, MEDIUMRAW, XLATE, UNICODE?

**Comment by legionus** [comment]
@Ricky-Tigg  Unknown mode appears when the console is not a terminal. I'm assuming you are running the utility in a terminal emulator. You can specify the `--console=DEV` option to specify a real terminal.
