### ISSUE TITLE
Is it even possible to meet the condition for the establishment of a pure terminal?

### ISSUE THREAD

**Issue by Ricky-Tigg** [legionus/kbd#116]
Hello. This report would have been in its place in the dedicated _Discussions_ section; the latter being disabled, I post here.

Text under the _Introduction_ header at https://kbd-project.org/

_The kbd project contains utilities for managing Linux console (Linux console, virtual terminals, keyboard, etc.)_.

Can you confirm that the above quote is indeed meant to express that the utilities provided by this program are not intended to be executed in an emulated terminal? Because I, despite all attempts to interpret it correctly, could not find any basis that could lead me to conclude in this way; notably _virtual terminals_.

I learned from one of your comments to one of my reports that the utilities were run on my system in a **terminal emulator**, and not in a pure terminal, in which these utilities are intended to operate. But what intrigued me, it's the fact that it exists reports here other than my own, therefore their authors must have been aware of some condition that had to be met in order to establish a pure terminal and so being able to execute those utilities according to their design. Yet I have no clue where they could have acquired such a knowledge by just reading the public documentation on the _kbd-project.org_ site.

Can it be so, that the condition for a pure terminal is somehow related to the _VT100_, a hardware terminal, workstation that is of type Teletype (TTY)? If I understood correctly, could this hardware be called _console_, _virtual terminal_, as opposed to a pure terminal? Knowing that nowadays, a terminal qualified as _emulator_ refers to a program that emulates the functionality of such a machine, can we conclude that this machine must have the ability to provide a pure terminal? Or is the achievement of a pure terminal tied to a special machine? Any suggestion would be welcome.

**Comment by legionus** [comment]
> Can you confirm that the above quote is indeed meant to express that the utilities provided by this program are not intended to be executed in an emulated terminal? 

Yes and no. You can use these utilities wherever you want (run from a terminal, a terminal emulator, or without a terminal at all). But you can only configure the terminal using them.

@Ricky-Tigg Tell me, what problem you want to solve by running these utilities ?

**Comment by legionus** [comment]
> `sudo loadkeys -C /dev/tty3 fi` works as intended. That was worth warning me, though if happening, the effect would have last as long as the session, thus would have ended by logging out.

Wrong. The terminal configuration is saved between logins until the system is rebooted.

Your changes were overridden by your linux distribution. I can suggest that your distribution uses systemd and then you need to configure the console (keymap and font) through the `/etc/vconsole.conf` config.

> My next task will be to set the font case.

```shell
man vconsole.conf
```

**Comment by legionus** [comment]
> 
> ```
> $ localectl
> System Locale: LANG=fi_FI.UTF-8
>     VC Keymap: fi
>    X11 Layout: fi
>     X11 Model: pc105
> ```
> 
> Is it expected that _VC Keymap_ remains unchanged as _fi_, so does not change to _us_?

The localectl shows the current configuration but not what you have loaded into the kernel. kbd utilities work at a lower level. systemd uses kbd utilities to configure the console.

> Is that governed by the /etc/vconsole.conf file?

@Ricky-Tigg Yes, use it.
