### ISSUE TITLE
showconsolefont: ERROR kdfontop.c:92

### ISSUE THREAD

**Issue by istenburg** [legionus/kbd#120]
When executing “showconsolefont”, I get the following error message
```
showconsolefont: ERROR kdfontop.c:92 get_font_kdfontop: ioctl(KDFONTOP): Das Argument ist ungültig
```
How can I fix this error?

**Comment by legionus** [comment]
@istenburg  Is the font displayed in the same time ?

**Comment by istenburg** [comment]
Yes is displayed at the same time

**Comment by legionus** [comment]
It looks very much like a relatively recent change broke support for tall fonts in kbd. Thank you for finding it!

https://github.com/torvalds/linux/commit/18365ebf23f3e713e5dd8e295c9a639295250f3c

**Comment by legionus** [comment]
`showconsolefont` tries to determine the font size and fails. Fortunately, in case of an error, the program uses the default value - 256 (number of glyphs in the font).

**Comment by legionus** [comment]
@istenburg I was wrong.  Your terminal is not in text mode. If you run `kbdinfo getmode` on terminal where you run `showconsolefont` I think the value will be `graphics`. Is it so ?

**Comment by istenburg** [comment]
Yes, the value is “graphics”

**Comment by istenburg** [comment]
I just booted into a text mode and “showconsolefont” is displayed without error.
However, the font is not according to the “vconsole.conf” and I have to enter “setfont” to load the correct font.

**Comment by legionus** [comment]
> However, the font is not according to the “vconsole.conf” and I have to enter “setfont” to load the correct font.

@istenburg The kernel has default fonts inside[1]. To change the font you need to load it early in the system boot process. I don't know for what reason systemd didn't do this. Better to ask them.

[1] https://github.com/torvalds/linux/blob/master/lib/fonts/font_8x16.c

**Comment by legionus** [comment]
Should be fixed in master.
