### ISSUE TITLE
setfont: Order of command-line arguments changed with kbd 2.7

### ISSUE THREAD

**Issue by nmeum** [legionus/kbd#122]
Hello!

I am not sure if this is intentional, but the [rewrite of the command-line argument parser](https://github.com/legionus/kbd/commit/aed486b760ccc7cdb0ae9a36b428bded6ea132c7) (included with kbd 2.7) seems to have changed the order in which command-line arguments can be supplied. Previously (i.e. prior to kbd 2.7), certain parameters (such as `-C`) had to be passed after the font name. For example:

    setfont my-fancy-font.psf.gz -C /dev/tty1

However, with kbd 2.7 this results in the following error message:

    setfont: Unable to find file: -C

This [breaks software such as OpenRC](https://github.com/OpenRC/openrc/pull/765) which passes -C after the font name. Why does OpenRC do that? Because the SYNOPSIS section in the `setfont(8)` man page recommends it:

```
SYNOPSIS
       setfont [-O font+umap.orig] [-o font.orig] [-om cmap.orig] [-ou
       umap.orig] [-N] [font.new ...] [-m cmap] [-u umap] [-C console] [-hH]
       [-f] [-v] [-V]
```

This is [still the case for the setfont man page in kbd-2.7](https://github.com/legionus/kbd/blob/v2.7/docs/man/man8/setfont.8.gen#L21). Hence,  I am opening this issue to figure out: Whether this is this a documentation issue (i.e. the `setfont(8)` man page needs to be updated) or if the regression in the argument parser is unintentional (i.e. its a bug in the code and we shouldn't update OpenRC and other users of setfont).

**Comment by tpowa** [comment]
My Archboot project also got hit by that.

**Comment by legionus** [comment]
Can you check the fix in the `for-master` branch ?

https://github.com/legionus/kbd/commit/cf9b00c2ec6b1a1c2444f1fc1b206b65d90a6b7f

**Comment by Polynomial-C** [comment]
> Can you check the fix in the `for-master` branch ?
> 
> [cf9b00c](https://github.com/legionus/kbd/commit/cf9b00c2ec6b1a1c2444f1fc1b206b65d90a6b7f)

For me it does fix it when being used with `openrc`.

**Comment by nmeum** [comment]
Yep, works for me as well. Thanks for the quick fix, much appreciated! 🙏

**Comment by legionus** [comment]
I'm sorry, too. I've rewritten the argument parsing to bring the behavior of setfont closer to that of utilities using gnu getopt. Unfortunately I missed that regression after all.

**Comment by nmeum** [comment]
> I'm sorry, too.

No worries, happens to the best of us :)
