### ISSUE TITLE
chvt

### ISSUE THREAD

**Issue by jonnygrant** [legionus/kbd#22]
Hello
Could chvt --help and --version be added?

$ chvt --help
Couldn't get a file descriptor referring to the console
$ chvt --version
Couldn't get a file descriptor referring to the console
$

**Comment by jonnygrant** [comment]
Saw in source -V was checked, so would add --version for that and also -h/--help

**Comment by legionus** [comment]
You are right. I will need to add.

**Comment by jonnygrant** [comment]
Many thanks!
