### ISSUE TITLE
simultaneous keyboard key repeats

### ISSUE THREAD

**Issue by eizanprime** [legionus/kbd#25]
kbd allows to set custom repeat rates etc (with kbdrate -set), but on linux is seems that simultaneous key presses are not supported (pressing a and o will produce aoooooooooooooooooooooooooo and not aoaoaoaoaoaoaoaoaoaoaoaoaoaoao which would be the expected behavior).

On windows simultaneous key repeats are supported, would it be possible to get this behavior in linux ?

Is there any way to tweak kbd in order to get this behavior ? 

Thank you very much

**Comment by legionus** [comment]
AFIK that is not supported by linux kernel. So, no.
