### ISSUE TITLE
Is there as way to increase the maximum character size in setfont?

### ISSUE THREAD

**Issue by BitJam** [legionus/kbd#27]
In order to get readable console characters on high dpi displays I scaled most of the Terminus fonts by a factor of two, creating fonts with heights from 40 to 64.  But setfont will not accept heights or widths greater than 32.

I imagine some buffer sizes would need to be increased to lift these limits or maybe there is a hard limit imposed elsewhere.

**Comment by legionus** [comment]
The font size limit is in the linux kernel and cannot be changed:

https://github.com/torvalds/linux/blob/c356dc4b540edd6c02b409dd8cf3208ba2804c38/drivers/tty/vt/vt.c#L4473-L4474

**Comment by BitJam** [comment]
Thanks for the info!
