### ISSUE TITLE
kbd-2.1.0 tests fail to build on musl due to <error.h>

### ISSUE THREAD

**Issue by marv** [legionus/kbd#28]
kbd-2.1.0 does not build on musl based systems (`x86_64-pc-linux-musl` in my case) due to the new usage of `<error.h>` in the tests:

```
libkbdfile-test01.c:4:10: fatal error: error.h: No such file or directory
 #include <error.h>
          ^~~~~~~~~
compilation terminated.
```

I'm not really sure what's the proper fix here. From a quick search I understand that `<error.h>` is a glibc-ism and that more standard conformant libc implementations such as musl don't provide that header.

An explanation on the musl mailing list[1] states the behaviour of the used `error` function as:
```
error() does the following:

1. sets the thread to uncancellable
2. flushes stdout
3. flocks stderr
4. calls (*error_print_progname)(), if non-NULL
5. printfs extern char *program_name, which is assumed to be defined
6. Converts *message into wchar_t *wmessage (that's right... it calls
alloca() and realloc() after you've already told it that it's in error...)
7. printfs whatever the caller puts in the format string (that's the
const char* in the arguments)
8. also formats the status and error number (which are the first two
int's in the arguments)
9. frees wmessage
10. increments error_message_count
11. funlocks stderr
12. sets the thread to cancellable
```

Are the tests relying in all of this behaviour? Or is it basically used to conviently print an error message and exit with the given error code? In that case I think I would be rather easy to provide an `error` function for libc's that don't provide the `<error.h>` header

[1] https://www.openwall.com/lists/musl/2014/06/29/8

**Comment by legionus** [comment]
oops! I mostly use glibc and sometimes I forget about the rest of libc. Sorry. I fixed the test build and added a build test with musl to Travis CI.
Thanks!
