### ISSUE TITLE
setfont doesn't invoke gzip?

### ISSUE THREAD

**Issue by nmeum** [legionus/kbd#32]
My Linux distribution (Alpine Linux) recently received an upgrade from kbd `2.0.4` to kbd `2.2.0`. I noticed that `2.2.0` behaves a bit different in regards to file handling:

* `setfont ter-v16n.psf.gz` → `Bad input file size`
* `setfont ter-v16n.psf` → works
* `setfont /usr/share/consolefonts/ter-v16n.psf.gz` → also works

The first setfont invocation definitely used to work with kbd `2.0.4`. Is it possible that the decompressor (gzip) is not invoked for the first invocation for some reason and kbd tries to parse the gzip compressed data and fails? `strace -f setfont ter-v16n.psf.gz` seems to confirm this hypothesis: https://tpaste.us/NKjk

**Comment by legionus** [comment]
Can you try to reproduce it on `master` ?

I tried but I didn’t succeed. I ran the command (log attached):
```
strace -fF -o setfont.log -e file ./setfont lat9w-10.psfu
``` 
[setfont.log](https://github.com/legionus/kbd/files/3522706/setfont.log)

**Comment by legionus** [comment]
ooops. I tested wrong case. sorry.

**Comment by legionus** [comment]
Please test current `master`.

**Comment by nmeum** [comment]
Can confirm that the current master fixes this bug.

**Comment by nmeum** [comment]
Thanks for the fast fix!
