### ISSUE TITLE
us.map maps Right Alt to AltGr and Shift+Tab to Alt+Tab.

### ISSUE THREAD

**Issue by crocket** [legionus/kbd#36]
* I have never seen a US layout keyboard with AltGr at the position of Right Alt. Using emacs ergonomically demands pressing two alt keys freely. GNU readline is an often-used program that also benefits from Right Alt.
* I don't see a good reason to map Shift+Tab to Alt+Tab unless parts of keymaps were forgotten or neglected.

For now, I use my own keymap that inherits us.map and linux-with-two-alt-keys and maps Alt+Tab to Alt+Tab and Shift+Tab to Shift+Tab

```
include "us.map"
include "linux-with-two-alt-keys"

alt keycode 15 = Meta_Tab
shift keycode 15 = F26
string F26 = "\033[Z"
```

I propose mapping Right Alt to Alt and Shift+Tab to `Esc[Z` and Alt+Tab to Meta_Tab in us.map or a (modern) variant of us.map. Perhaps, it could be named us-english.map.

**Comment by crocket** [comment]
My suggestion was to add a new map with modifications.

**Comment by legionus** [comment]
ok. I will add it as `us1`.

**Comment by legionus** [comment]
https://github.com/legionus/kbd/blob/master/data/keymaps/i386/qwerty/us1.map
