### ISSUE TITLE
setfont doesn't work on console if nothing was echo-ed before

### ISSUE THREAD

**Issue by kogaba** [legionus/kbd#38]
Hi
When I tried to set consolefont with initrd and also used the quiet kernel parameter, the character set does not changed, because nothing was echoed to the console before setfont.
My workaround now is to add an echo -en "a\010 \010" before setfont as described here:
https://bugs.archlinux.org/task/65148#comment190031

Not sure if it's a setfont issue or kernel issue
Cheers

**Comment by legionus** [comment]
The setfont only uses ioctl's for configuration. I also [configure](https://github.com/osboot/make-initrd/blob/d926fdb2a351af6459f59a6e969d7a2fa567f73d/features/kbd/data/lib/uevent/handlers/console/100-configure#L75) the console in initrd but have not seen such problems. It looks like you hit the problem in [systemd](https://github.com/systemd/systemd/pull/15479).

**Comment by legionus** [comment]
ok. feel free to reopen.
