### ISSUE TITLE
Please use HTTPS URL in GitHub description

### ISSUE THREAD

**Issue by paulmenzel** [legionus/kbd#39]
To save one redirect, could you please use the HTTPS URL in the GitHub description (top line)?

> Mirror of http://git.kernel.org/cgit/linux/kernel/git/legion/kbd.git

PS: I believe the description supports also a separate Web site(?) field. Maybe https://kbd-project.org/ could be added there?

**Comment by legionus** [comment]
Good catch! Thanks!
