### ISSUE TITLE
dumpkeys-bkeymap test fails on big-endian processors

### ISSUE THREAD

**Issue by floppym** [legionus/kbd#40]
We encountered a test failure on Gentoo Linux.
```
FAIL: dumpkeys-bkeymap
======================

++ readlink -ev .
+ cwd=/var/tmp/portage/sys-apps/kbd-2.2.0-r2/work/kbd-2.2.0/tests
+ cd /var/tmp/portage/sys-apps/kbd-2.2.0-r2/work/kbd-2.2.0/tests
+ rc=0
++ mktemp ./temp.XXXXXXXXX
+ temp=./temp.HK4tsKB7q
+ datadir=.
+ ./libkeymap-bkeymap ./../data/keymaps/i386/qwerty/defkeymap.map
+ cmp -s ./data/dumpkeys-bkeymap/bkeymap.bin ./temp.HK4tsKB7q
+ rc=1
+ '[' 1 '!=' 0 ']'
+ printf 'failed\n'
failed
+ exit 1
FAIL dumpkeys-bkeymap (exit status: 1)
```
This test dumps a keymap to a binary file, and compares it with some pre-generated reference data.

The binary data contains multi-byte integer values in the machine's native byte order.

The reference data appears to have been generated on a little-endian machine, so this test fails on big-endian machines.

See the Gentoo Linux bug report for more details.

https://bugs.gentoo.org/727822

**Comment by floppym** [comment]
We think this is the problematic code in 2.2.0.

https://github.com/legionus/kbd/blob/v2.2.0/src/libkeymap/dump.c#L77

This was updated to a 2-byte value for 2.2.90, but the value is still stored in native byte order.

https://github.com/legionus/kbd/blob/v2.2.90/src/libkeymap/dump.c#L82

**Comment by legionus** [comment]
Yep. The `data/dumpkeys-bkeymap/bkeymap.bin` was created on a little-endian machine.

**Comment by dmage** [comment]
@legionus how can bkeymap files be used?

**Comment by legionus** [comment]
A busybox has a `loadkmap` utility (mini micro loadkeys):

https://git.busybox.net/busybox/tree/console-tools/loadkmap.c

**Comment by floppym** [comment]
In that busybox applet, the binary data is copied directly into a struct entry, and then passed to the kernel via `ioctl`. I would guess the kernel expects values in native byte order.

So, either both busybox and lk_dump_bkeymap would need to be adjusted to use a consistent on-disk format, or the dumpkeys-bkeymap test needs to account for differences in native byte order.

**Comment by floppym** [comment]
It looks like this test might be skipped after this commit. I don't think we have tested version 2.2.90 on Gentoo.

https://github.com/legionus/kbd/commit/a4dc98328ce62041da257dd77c84aeecebce973c#diff-7dd1fc63f8aa74879deaf8496dc94d14

I think this also skips the test on amd64 when it is not be executed under Travis. I would guess that's an accident.
