### ISSUE TITLE
It is not a good idea to mark the empty string for translation

### ISSUE THREAD

**Issue by goeranu** [legionus/kbd#41]
In `dumpkeys.c` the description of the `-S` option is the empty string:

    { "-S, --shape={2|4|8|16}", _("") },

This is not a good idea.  Obviously it is of course pointless an empty string.  In addition, ss an implementation idiosyncrasy of `pot` files, the translation of the empty string is used to hold the header of the translation, listing things like project id, dates, last translator and team, etc.  If the gettext library doesn't handle the empty string as a special case, I haven't checked recently but it didn't use to, the result of `dumpkeys --help` will contain this header in the output, most likely not what you want! :smiley: 

While waiting for a proper help text, it would be better to use some dummy nonempty string, just a space for example.

**Comment by legionus** [comment]
This has already been fixed. Thank.

https://github.com/legionus/kbd/commit/e8f07241d4e12c56f7ad96e7706d6613f833e1cd
