### ISSUE TITLE
installation of libtswrap.{la,so,a}: is it intentional?

### ISSUE THREAD

**Issue by xry111** [legionus/kbd#46]
From kbd-2.3.0, it installs a library named `libtswrap`.  But it's in the `tests` directory, and it does not ship any headers.  The release note also doesn't metion it. So I wonder if the installation of it is not intentional.

**Comment by legionus** [comment]
@xry111 Ooops! This is of course an internal library. Thanks for noticing!

**Comment by legionus** [comment]
Fixed. Thanks!
https://github.com/legionus/kbd/commit/510ca0134348bde6608a71aa92f4e0edf9dde949
