### ISSUE TITLE
There is no CapsLock indication of CapsLock key using Caps Lock LED on the keyboard while using plain TTY (such as Ctrl+Alt+F1)

### ISSUE THREAD

**Issue by N0rbert** [legionus/kbd#55]
Steps to reproduce:
1. Have minimal Ubuntu 20.04 LTS installed with all default settings and minimal set of packages on the laptop or desktop with physical CapsLock / Caps Lock LED indicator on the case or keyboard.
2. Boot the system using default settings
3. Login to the system
4. Press `<Caps Lock>` key, enter some letters in CAPITALS (while CapsLock LED is on)
5. Press `<Caps Lock>` key again, enter some letters in lowercase (while CapsLock LED is off)

Expected results:
* CapsLock key toggles CapsLock LED, the LED state indicates current CapsLock key function

Actual results:
* CapsLock LED is always off

Downstream bug-report: 

* https://pad.lv/1925141

**Comment by legionus** [comment]
According to [comment #3](https://bugs.launchpad.net/ubuntu/+source/kbd/+bug/1925141/comments/3)  the bug in the dpkg package.

**Comment by N0rbert** [comment]
The bug is really in `kbd` package. Removal of `kbd` package solves the CapsLock LED issue. 
The command in the [comment #3](https://bugs.launchpad.net/ubuntu/+source/kbd/+bug/1925141/comments/3) is used to remove executable bit from all [`kbd` executables](https://packages.ubuntu.com/focal/amd64/kbd/filelist).

If you can please test and confirm this bug on any modern Ubuntu version.

**Comment by legionus** [comment]
The steps to reproduce described in this issue refer to kbd only indirectly. I am not using ubuntu, but I suspect some scripts in ubuntu are calling `setleds` utility with wrong arguments.

**Comment by legionus** [comment]
It looks like the issue has been resolved.
