### ISSUE TITLE
hex colors

### ISSUE THREAD

**Issue by oskude** [legionus/kbd#60]
every _things_ colors in my system can be defined by "standard" rgb hex color string, eg #`1122AA`, so i was wondering/hoping if kbd-project would be intrerested in such feature?

if yes, i wonder if it's worth to add such feature to `setvtrgb`, write a new tool, or ask if https://github.com/EvanPurkhiser/linux-vt-setcolors would like to be added to kbd-project?

**Comment by legionus** [comment]
Yes. It would be an interesting feature. I like it.

**Comment by legionus** [comment]
I don't know how best to do this yet. It seems like it should be part of setvtrgb but I'm not sure if I can add support for the new format.

**Comment by oskude** [comment]
> I'm not sure if I can add support for the new format

you mean as in write the code, or something else?

code i can take a try (i know the basics of c ;P) and for usage i could see 2 possibilities:

1. use a file format to define if dec or hex values
2. use an option to specify which format

if we use a file format like this for hex values:

```
#112233
#445566
#AABBCC
... all the 16 colors
```

we could simply check the first char in file for "#".

**Comment by legionus** [comment]
> > I'm not sure if I can add support for the new format
> 
> you mean as in write the code, or something else?

Writing the code is not a problem. It's harder to make support user-friendly.

> code i can take a try (i know the basics of c ;P) and for usage i could see 2 possibilities:
> 
>     1. use a file format to define if dec or hex values
> 
>     2. use an option to specify which format

I also thought about these two possibilities. I like your format.

> 
> if we use a file format like this for hex values:
> 
> ```
> #112233
> #445566
> #AABBCC
> ... all the 16 colors
> ```
> 
> we could simply check the first char in file for "#".

This format will differ from the linux-vt-setcolors format, but I like it better.

**Comment by legionus** [comment]
@oskude I plan to release a new version soon. Should I wait for your patch ?

**Comment by oskude** [comment]
@legionus oh, didn't realise you wanted code from me :) i already got a simple patch done (for the reading file part), and wonder what else should i update/add? (docs, tests, etc?).

depending on how much is still to do, i could be done today or tomorrow.

you want the patch as comment here or a github pull request or?

ps. please note that i never tinkered with kbd source before, so dunno where's what.

**Comment by legionus** [comment]
> oh, didn't realise you wanted code from me :)

https://github.com/legionus/kbd/issues/60#issuecomment-917439244 -- you told me that you can try and outlined good ideas for implementation. I thought that you would do it.

> i already got a simple patch done (for the reading file part), and wonder what else should i update/add? (docs, tests, etc?).

Documentation and tests are always welcome! :))

> you want the patch as comment here or a github pull request or?

@oskude You can make it as pull request.

**Comment by oskude** [comment]
@legionus do you happen to know how to run `.travis.yml` locally?

**Comment by legionus** [comment]
travis runs:
```
./autogen.sh
./configure --enable-optional-progs
make
make check CHECK_KEYWORDS="unittest e2e"
```
Some tests will be skipped because they require root privileges.
