### ISSUE TITLE
Euro at Portuguese keyboards

### ISSUE THREAD

**Issue by Azureit** [legionus/kbd#63]
The Portuguese keyboard layout pt-latin1.map needs **include "euro2.map"** to be complete, like the de-latin1.map already do.
Most Portuguese keyboards, apart from having the euro at **E** key have it at **5** key too.

![1920px-KB_Portuguese svg](https://user-images.githubusercontent.com/1774476/142893886-b53f6270-5c9d-4713-91d9-4e352b8de768.png)
![image](https://user-images.githubusercontent.com/1774476/142892344-53879801-7c5d-4adb-9ad4-bf77fc69b36e.png)

**Comment by legionus** [comment]
Thanks! Done.
