### ISSUE TITLE
Incorrect acentuation pt-latin9

### ISSUE THREAD

**Issue by Azureit** [legionus/kbd#64]
At the console, if I set keymap to pt-latin9, the characters accentuation will be wrong.
e.g. **é** would be displayed **´e**
To correct this I need to change the keymap to pt-latin1

**Comment by legionus** [comment]
```diff
diff --git a/data/keymaps/i386/qwerty/pt-latin9.map b/data/keymaps/i386/qwerty/pt-latin9.map
index 01204c6..f353d42 100644
--- a/data/keymaps/i386/qwerty/pt-latin9.map
+++ b/data/keymaps/i386/qwerty/pt-latin9.map
@@ -7,6 +7,7 @@ keymaps 0-2,4,6,8,12
 alt_is_meta
 include "qwerty-layout"
 include "linux-with-alt-and-altgr"
+include "compose.latin"
 strings as usual

 keycode   1 = Escape
```
Can this fix the problem?

**Comment by Azureit** [comment]
> ```diff
> diff --git a/data/keymaps/i386/qwerty/pt-latin9.map b/data/keymaps/i386/qwerty/pt-latin9.map
> index 01204c6..f353d42 100644
> --- a/data/keymaps/i386/qwerty/pt-latin9.map
> +++ b/data/keymaps/i386/qwerty/pt-latin9.map
> @@ -7,6 +7,7 @@ keymaps 0-2,4,6,8,12
>  alt_is_meta
>  include "qwerty-layout"
>  include "linux-with-alt-and-altgr"
> +include "compose.latin"
>  strings as usual
> 
>  keycode   1 = Escape
> ```
> 
> Can this fix the problem?
Yes, that patch fix this accentuation issue with pt-latin9
Thanks.
