### ISSUE TITLE
setfont.8.in:  "-f" option seems to be a no-op, but is not documented

### ISSUE THREAD

**Issue by ahmogit** [legionus/kbd#65]
Various older posts on stack exchange, reddit, etc., show `setfont` examples using `-f` to specify the font file. Yet there doesn't seem to be any mention of the `-f` option in setfont.8.in, or in the help blurb, and the option is accepted without any diagnostic.  Has it perhaps been deprecated?

Superficially at least, `-f` appears to be a no-op, i.e. `setfont -f foofont` appears to produce the same result as `setfont foofont`. But it would be nice if that were confirmed in the documentation. Imo, it's not unreasonable for a user to wonder if `-f` might be subtly different in some silent way from not specifying it at all.

Thanks.

**Comment by legionus** [comment]
Yes, `-f` should be documented, but this option is not deprecated. The `-f` option means `force`. In some cases, this still allows the font to be loaded.

**Comment by ahmogit** [comment]
OK, thanks for the explanation.

If you can provide a slightly more detailed explanation of the semantics of "force" and "in some cases", I'll be happy to take a shot at adding a blurb to the man page with that info and submitting a pull request.

**Comment by legionus** [comment]
@ahmogit For now, `-f` allows to load into kernel an empty unimap. An empty unimap is a very strange case, but someone might be using it. So this option exists, which forces `setfont` to make a syscall with an empty list.
