### ISSUE TITLE
Make libkfont public API

### ISSUE THREAD

**Issue by marcosfrm** [legionus/kbd#69]
It would be nice call `kfont_load_fonts()` from my C code instead of fork/exec `setfont` (`./configure --enable-libkfont` or so).

Thanks.

**Comment by legionus** [comment]
@marcosfrm I have not made this library public because I am not sure that its API is convenient and sufficient for using this library. For now it has only one user - `setfont`. 

You can try to use the current API and if it is enough, then in the new version I will make this library public.

**Comment by marcosfrm** [comment]
My use case is simple: just load one font to `/dev/tty1`.

Quick 'n dirty test:

```c
#include <fcntl.h>

// -------------------------------------
struct kfont_context {
	const char *progname;
	int verbose;
	void (*log_fn)(struct kfont_context *, int, const char *, int,
		const char *, const char *, va_list);

	unsigned int options;

	const char *const *mapdirpath;
	const char *const *mapsuffixes;

	const char *const *fontdirpath;
	const char *const *fontsuffixes;

	const char *const *partfontdirpath;
	const char *const *partfontsuffixes;

	const char *const *unidirpath;
	const char *const *unisuffixes;
};

int kfont_init(const char *prefix, struct kfont_context **ctx);

void kfont_inc_verbosity(struct kfont_context *ctx);

int kfont_load_font(struct kfont_context *ctx, int fd, const char *ifil,
		unsigned int iunit, unsigned int hwunit, int no_m, int no_u);
// -------------------------------------

int main(void)
{
    int fd;
    struct kfont_context *fctx;

    fd = open("/dev/tty1", O_RDWR);

    // ...

    kfont_init(NULL, &fctx);
    kfont_inc_verbosity(fctx);
    kfont_load_font(fctx, fd, "Lat2-Terminus16", 0, 0, 0, 0);

    // ...
}
```

Then linked against `kbd-2.4.0/src/{libkfont/.libs/libkfont.a,libkbdfile/.libs/libkbdfile.a}` (with 501efd7b873e1462da986f763398ea8d98df2767 applied).

![kfont](https://user-images.githubusercontent.com/12900645/151077658-a6027af1-367c-41f3-b19a-a9c438793eb5.png)

It works fine. I could not find a function to free `kfont_context` and documentation about `errno` being set on error. Also even without `kfont_inc_verbosity()` errors are still printed -- can it be silent?

**Comment by legionus** [comment]
@marcosfrm thanks for testing. I made a branch with fixes [1]. The functions return 0 on success and negative value [2] in case of error. 

[1] https://github.com/legionus/kbd/tree/libkfont-public-v1
[2] /usr/include/sysexits.h

**Comment by marcosfrm** [comment]
Will not 3c91ce7cf51c89c3ac7d4587b7e001df4ea69a64 break `setfont` binary expected output (no error messages without `-v`)?

`kfont_set_logger(fctx, NULL);` is enough for me I think.

**Comment by legionus** [comment]
> Will not [3c91ce7](https://github.com/legionus/kbd/commit/3c91ce7cf51c89c3ac7d4587b7e001df4ea69a64) break `setfont` binary expected output (no error messages without `-v`)?

@marcosfrm Yes, it will. To preserve compatibility `LOG_CRIT` should be replaced by `LOG_ERR`.

> `kfont_set_logger(fctx, NULL);` is enough for me I think.

Yes, but in this case you won't see any error at all.

**Comment by marcosfrm** [comment]
https://github.com/legionus/kbd/blob/268a9348616ac827ad53b9b14630a03e80a2af66/src/libkeymap/libkeymap.pc.in#L10

https://github.com/legionus/kbd/blob/268a9348616ac827ad53b9b14630a03e80a2af66/src/libkfont/libkfont.pc.in#L10

`libfindfile` was renamed to `libkbdfile`...

**Comment by legionus** [comment]
@marcosfrm Good catch! Thanks!

**Comment by marcosfrm** [comment]
Any news?

**Comment by legionus** [comment]
Ops. Sorry. I was hoping to be able to add support for xkb keymaps in a future release, but apparently the libxkbcommon developers are being delayed in implementing the missing API. I will prepare a release without xkb.

Release will be soon.

**Comment by legionus** [comment]
v2.5-rc1
