### ISSUE TITLE
euro2 include breaks the pt-latin1 layout

### ISSUE THREAD

**Issue by BrunoMSantos** [legionus/kbd#78]
The recently released v2.5.0 includes the patch e29babc5a012c21ea72a526fd3942468ce88c581 from issue #63 which seems well reasoned and indeed needed. However it also breaks the `pt-latin1` layout in an up to date Arch Linux distribution. `mkinitcpio` with the `keymap` hook, `loadkeys` or the `systemd-vconsole-setup` all fail with the error:

```
cannot open include file euro2
syntax error, unexpected ERROR
```

I don't know enough about the file format to know whether they have any error though. They look fine to me though, and I'm, in no way confident the issue lies here.

That said, rolling back to v2.4.0 fixes it for me for the time being.

**Comment by BrunoMSantos** [comment]
Ok, I think I've found the issue. The include line reads:
```
include "euro2"
```
But I believe it should read:
```
include "euro2.map"
```

**Comment by diogotcorreia** [comment]
Can confirm this is also happening to me.
Switching to `pt-latin9` temporarily fixes the issue as well.
