### ISSUE TITLE
is-latin1 circumflex

### ISSUE THREAD

**Issue by eidurkr** [legionus/kbd#81]
data/keymaps/i386/qwerty/is-latin1.map
Lines 79-80

The standard functionality is commented out in favour of a level-2 circumflex. This is fine, but the circumflex should also be available in its original level-3 position.

Current version:
keycode  40 = dead_acute       asciicircum
#keycode  40 = dead_acute       dead_acute       asciicircum

My proposal:
keycode  40 = dead_acute       asciicircum       asciicircum
#keycode  40 = dead_acute       dead_acute       asciicircum

**Comment by legionus** [comment]
Ok. Applied.
