### ISSUE TITLE
Keymap problem

### ISSUE THREAD

**Issue by pandom79** [legionus/kbd#87]
Hi,
I have a problem with "loadkeys" command when I enter the luks password.
It cannot set the keymap.
The error is the following : 
loadkeys: /usr/share/kbd/keymaps/i386/qwerty/it.map:31: cannot open include file linux-with-alt-and-altgr.
I have this file in /usr/share/kbd/keymaps/i386/include/linux-with-alt-and-altgr.inc.

How could i resolve it ?
Best regards

**Comment by legionus** [comment]
@pandom79 loadkeys is called in initrd or do you run it manually?

**Comment by pandom79** [comment]
@legionus 
It's called from initrd (dracut).
In the doubt, I opened another issue on dracut git repo.
https://github.com/dracutdevs/dracut/issues/1933

**Comment by legionus** [comment]
@pandom79 The guys from dracut forgot to put in the initrd files that are used by keymap. They may also need to put decompression utilities (gzip, bzip2, etc.) in the initrd if the files are compressed. The loadkeys does not link with compression libraries but calls utilities.

**Comment by pandom79** [comment]
@legionus 
Yes, it's a dracut problem.
I added the various include files in dracut conf and it worked.
`install_items+=" /usr/share/kbd/keymaps/i386/include/compose.inc /usr/share/kbd/keymaps/i386/include/linux-keys-bare.inc /usr/share/kbd/keymaps/i386/include/linux-keys-extd.inc /usr/share/kbd/keymaps/i386/include/linux-with-alt-and-altgr.inc /usr/share/kbd/keymaps/i386/include/linux-with-modeshift-altgr.inc /usr/share/kbd/keymaps/i386/include/linux-with-two-alt-keys.inc /usr/share/kbd/keymaps/i386/include/qwerty-layout.inc "`
Maybe, only that is enough. 
I compress initrd with zstd which is not present in intrd and it works anyway. 
For this reason, I think no need to have gzip, xz...etc inside it.
Thanks so much for collaboration.
