### ISSUE TITLE
Dvorak german missing

### ISSUE THREAD

**Issue by mcr42** [legionus/kbd#88]
Strange as it may seem, there is no german dvorak layout in the package.
I would see to that, but I'm not familiar with the format kbd uses.
If there's a hint on how to convert an existing german dvorak map, I'd be happy to help.

**Comment by mcr42** [comment]
Digging through the systems I use, I found the file dvorak-de.kmap.gz from Debian's console-data works reasonably well.
Would there be a problem to just include it under the name dvorak-de.map.gz ?
[dvorak-de.map.gz](https://github.com/legionus/kbd/files/9847192/dvorak-de.map.gz)

**Comment by legionus** [comment]
Hi! @mcr42 I don't mind at all to add dvorak-de.kmap from debian's console-data package. To be honest, I don't know why they keep them separate.

**Comment by legionus** [comment]
Added.
