### ISSUE TITLE
screendump missing in arch package?

### ISSUE THREAD

**Issue by Githopp** [legionus/kbd#91]
Hey could be a noob question, but I installed the arch kbd package (pacman -S kbd) and are missing the screendump programm.
Is this a bug? I dont know where to ask, if the arch package differs from the debian one.

I now copied the usr/bin/screendump from my debian machine to my arch machine, but thats not really a fix.

**Comment by legionus** [comment]
The screendump is not built by default (it is optional). In order for optional utilities to be built, the `--enable-optional-progs` option must be used. The archlinux build does not use this option:

https://github.com/archlinux/svntogit-packages/blob/packages/kbd/trunk/PKGBUILD#L46

**Comment by legionus** [comment]
@Githopp You should ask the archlinux maintainers to add the option to their build.

**Comment by Githopp** [comment]
Thank you very much for the prompt reply! I will try that.
