### ISSUE TITLE
Feature request: restore default font (setfont)

### ISSUE THREAD

**Issue by Tecol87** [legionus/kbd#95]
On a lot of distributions, the default font (e.g. ter-u32b) is not available as file since terminus-font is not installed. The default font can be restored with [this code](https://unix.stackexchange.com/questions/710337/how-can-i-restore-the-linux-console-font-back-to-the-kernel-built-in-font).
This can be important, when the current font is garbage (https://github.com/legionus/kbd/issues/94) or not as readable as the default font.

**Comment by legionus** [comment]
I found a bug in the implementation of the -R option. By fixing it this option does exactly what you want it to do.
